name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64cbc6d6fc95fabce6d532a840638bb97077ba24e7fb5a8ebd3c3b3507243ddd"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
