name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f625301dafefce035424432ad84de27737b5101aa2ce93321110a6d336066e12"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
