name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed311eaf1255b7f852db496a72ce6aca7ab691ec9864ff249815d1fe0d7814da"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
