name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa67e862571c3932318b670a13e285980566fa67ad90fe2b5233982ecbfd0c8"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
