name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08c609ee7e6f52b6ede9d19395a98bea221c4d4d62c56d0cfbadbe5c366bdf5b"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
