name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2453c38dc1f20f79d9f59c3c8e32652a3cf115fba457ecbf51bc0d7bb77dcd8"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
