name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4486274dfbcf936b8223f61e1f21e0f7f8140153cf71a30be408d68ebe3d4dad"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
