name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bffe36d5e6fddac83bbe97a5117de6e33a26e1159791c57ebce517a267e907fe"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
