name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e3f7806f7e3d8780ac4a385f82b449348a5114cec1fe30532113ad696ed52b5"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
