name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3f1b0ba38ce532cbffabdd1d9fb557add7e7fbc58714a31ce2e903149c55adb"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
