name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b606036b4d5f275cc0cefe376437b146087ee4b249c786806786f65d15b91b3"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
