name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c46aadeea287ff9212f32e2ebd3f7211cfdc35800e6e0a7251823538fce0ff7"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
