name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "403c7f28d8ac7d706cfb720678dce8150ae93d4b1ed67ecf13c701ea24ce316c"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
