name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa5de3b9121b675886b1640e462c74f4d877cfdec81637b834a28a2f2f73aa4d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
