name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f04b9913f112867aafc447c85fa80e7026dc08bb74614959c9b7a7af3abb60f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
