name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5107f9866ea9bd29e48914165ab218a2018beafdeb1e2f9aa672a2a1f2126268"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
