name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ef634019029c744d26733fdca47d1fc958a67f82ebaab00a101ca46046775f7"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
