name = "Thaumcraft4Pack"
author = "PufferTeam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eacca733d5fe754d3e763acb88f77488128185dca9d4611970fe222f3c49740d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
