import minetweaker.item.IItemStack;
import minetweaker.oredict.IOreDictEntry;
import minetweaker.data.IData;
import mods.nei.NEI;

var itemsToRemove = [
	<minecraft:wooden_sword:*>,
	<minecraft:wooden_shovel:*>,
	<minecraft:wooden_pickaxe:*>,
	<minecraft:wooden_axe:*>,
	<minecraft:wooden_hoe:*>,
	<minecraft:stone_sword:*>,
	<minecraft:stone_shovel:*>,
	<minecraft:stone_pickaxe:*>,
	<minecraft:stone_axe:*>,
	<minecraft:stone_hoe:*>,
	<minecraft:diamond_sword:*>,
	<minecraft:diamond_shovel:*>,
	<minecraft:diamond_pickaxe:*>,
	<minecraft:diamond_axe:*>,
	<minecraft:diamond_hoe:*>,
	<minecraft:diamond_helmet:*>,
	<minecraft:diamond_chestplate:*>,
	<minecraft:diamond_leggings:*>,
	<minecraft:diamond_boots:*>,
	<aether_legacy:skyroot_pickaxe:*>,
	<aether_legacy:skyroot_axe:*>,
	<aether_legacy:skyroot_shovel:*>,
	<aether_legacy:skyroot_sword:*>,
	<aether_legacy:holystone_pickaxe:*>,
	<aether_legacy:holystone_axe:*>,
	<aether_legacy:holystone_shovel:*>,
	<aether_legacy:holystone_sword:*>,
	<thebetweenlands:weedwoodSword:*>,
	<thebetweenlands:weedwoodPickaxe:*>,
	<thebetweenlands:weedwoodAxe:*>,
	<thebetweenlands:weedwoodShovel:*>,
	<chisel:limestone_slab:*>,
	<chisel:marble_slab:*>,
	<chisel:marble_pillar_slab:*>,
	<chisel:aluminum_stairs.0>,
	<chisel:aluminum_stairs.0:8>,
	<chisel:aluminum_stairs.1>,
	<chisel:aluminum_stairs.1:8>,
	<chisel:aluminum_stairs.2>,
	<chisel:aluminum_stairs.2:8>,
	<chisel:limestone_stairs.0>,
	<chisel:limestone_stairs.0:8>,
	<chisel:limestone_stairs.1>,
	<chisel:limestone_stairs.1:8>,
	<chisel:limestone_stairs.2>,
	<chisel:limestone_stairs.2:8>,
	<chisel:limestone_stairs.3>,
	<chisel:limestone_stairs.3:8>,
	<chisel:limestone_stairs.4>,
	<chisel:limestone_stairs.4:8>,
	<chisel:limestone_stairs.5>,
	<chisel:limestone_stairs.5:8>,
	<chisel:limestone_stairs.6>,
	<chisel:limestone_stairs.6:8>,
	<chisel:limestone_stairs.7>,
	<chisel:limestone_stairs.7:8>,
	<chisel:ice_stairs.0>,
	<chisel:ice_stairs.0:8>,
	<chisel:ice_stairs.1>,
	<chisel:ice_stairs.1:8>,
	<chisel:ice_stairs.2>,
	<chisel:ice_stairs.2:8>,
	<chisel:ice_stairs.3>,
	<chisel:ice_stairs.3:8>,
	<chisel:ice_stairs.4>,
	<chisel:ice_stairs.4:8>,
	<chisel:ice_stairs.5>,
	<chisel:ice_stairs.5:8>,
	<chisel:ice_stairs.6>,
	<chisel:ice_stairs.6:8>,
	<chisel:ice_stairs.7>,
	<chisel:ice_stairs.7:8>,
	<chisel:marble_stairs.0>,
	<chisel:marble_stairs.0:8>,
	<chisel:marble_stairs.1>,
	<chisel:marble_stairs.1:8>,
	<chisel:marble_stairs.2>,
	<chisel:marble_stairs.2:8>,
	<chisel:marble_stairs.3>,
	<chisel:marble_stairs.3:8>,
	<chisel:marble_stairs.4>,
	<chisel:marble_stairs.4:8>,
	<chisel:marble_stairs.5>,
	<chisel:marble_stairs.5:8>,
	<chisel:marble_stairs.6>,
	<chisel:marble_stairs.6:8>,
	<chisel:marble_stairs.7>,
	<chisel:marble_stairs.7:8>,
	<chisel:packedice_stairs.0>,
	<chisel:packedice_stairs.0:8>,
	<chisel:packedice_stairs.1>,
	<chisel:packedice_stairs.1:8>,
	<chisel:packedice_stairs.2>,
	<chisel:packedice_stairs.2:8>,
	<chisel:packedice_stairs.3>,
	<chisel:packedice_stairs.3:8>,
	<chisel:packedice_stairs.4>,
	<chisel:packedice_stairs.4:8>,
	<chisel:packedice_stairs.5>,
	<chisel:packedice_stairs.5:8>,
	<chisel:packedice_stairs.6>,
	<chisel:packedice_stairs.6:8>,
	<chisel:packedice_stairs.7>,
	<chisel:packedice_stairs.7:8>,
	<jaff:iron_nugget>,
	<ForgeMicroblock:sawStone>,
	<etfuturum:quartz_bricks>,
	<etfuturum:red_netherbrick>,
	<etfuturum:red_netherbrick:1>,
	<etfuturum:red_netherbrick:2>,
	<etfuturum:red_netherbrick_slab>,
	<etfuturum:red_netherbrick_stairs>,
	<etfuturum:purpur_block>,
	<etfuturum:purpur_pillar>,
	<etfuturum:end_bricks>,
	<etfuturum:wooden_armorstand>,
	<etfuturum:smooth_red_sandstone_slab>,
	<etfuturum:smooth_red_sandstone_stairs>,
	<netherlicious:QuartzWall>,
	<netherlicious:QuartzWall:3>,
	<netherlicious:dye:1>,
	<netherlicious:dye>,
	<netherlicious:dye:2>,
	<netherlicious:Nugget>,
	<netherlicious:Stem2:2>,
	<netherlicious:Stem2:3>,
	<netherlicious:FullWood:6>,
	<netherlicious:FullWood:7>,
	<BiomesOPlenty:misc:5>,
	<BiomesOPlenty:misc:9>,
	<BiomesOPlenty:misc:6>,
	<BiomesOPlenty:misc:8>,
	<BiomesOPlenty:misc:7>,
	<BiomesOPlenty:mudBricks>,
	<BiomesOPlenty:stoneSingleSlab>,
	<BiomesOPlenty:mudBricksStairs>,
	<BiomesOPlenty:gemOre:15>,
	<BiomesOPlenty:gemOre:14>,
	<BiomesOPlenty:gems:7>,
	<Pistronics2:Block of Camou>,
	<Pistronics2:Motion Block>,
	<gravestone:death_info>,
	<TravellersGear:armorstand>,
	<TravellersGear:simpleGear:5>,
	<TravellersGear:simpleGear:4>,
	<TravellersGear:simpleGear:2>,
	<TravellersGear:simpleGear:3>,
	<witchery:ingredient:52>,
	<witchery:ingredient:53>,
	<Botania:stone:*>,
	<Botania:stone1Stairs:*>,
	<Botania:stone9Stairs:*>,
	<Botania:stone0Wall:1>,
	<Botania:stone1Slab:*>,
	<Botania:stone9Slab:*>,
	<Botania:endStoneBrick>,
	<VillageNames:prismarine:*>,
	<VillageNames:prismarine_shard>,
	<VillageNames:prismarine_crystals>,
	<VillageNames:sea_lantern>
] as IItemStack[];

var oresToRemove = [
	<Thaumcraft:ItemNugget:1>,
	<Thaumcraft:ItemNugget:2>,
	<Thaumcraft:ItemNugget:3>,
	<Thaumcraft:ItemNugget:4>,
	<etfuturum:copper_ingot>,
	<GardenStuff:iron_nugget>,
	<ForbiddenMagic:FMResource:2>,
	<TConstruct:oreBerries:0>,
	<TConstruct:oreBerries:1>,
	<TConstruct:oreBerries:2>,
	<TConstruct:oreBerries:3>,
	<TConstruct:oreBerries:4>,
	<Mekanism:OreBlock:1>,
	<Mekanism:OreBlock:2>,
	<Mekanism:DeepslateOreBlock:1>,
	<Mekanism:DeepslateOreBlock:2>,
	<Mekanism:Dust>,
	<Mekanism:Dust:1>,
	<Mekanism:Dust:2>,
	<Mekanism:Dust:3>,
	<Mekanism:Dust:4>,
	<Mekanism:Dust:5>,
	<Mekanism:Dust:6>,
	<Mekanism:Ingot>,
	<Mekanism:Ingot:2>,
	<Mekanism:Ingot:3>,
	<Mekanism:Ingot:4>,
	<Mekanism:Ingot:5>,
	<Mekanism:Ingot:6>,
	<Mekanism:Ingot:7>,
	<Mekanism:BasicBlock:1>,
	<Mekanism:BasicBlock:5>,
	<Mekanism:BasicBlock:12>,
	<Mekanism:BasicBlock:13>,
	<Mekanism:OtherDust:1>,
	<ImmersiveEngineering:ore:0>,
	<ImmersiveEngineering:ore:1>,
	<ImmersiveEngineering:ore:2>,
	<ImmersiveEngineering:ore:3>,
	<ImmersiveEngineering:ore:4>,
	<ImmersiveEngineering:storage:0>,
	<ImmersiveEngineering:storage:2>,
	<ImmersiveEngineering:storage:3>,
	<ImmersiveEngineering:storage:4>,
	<ImmersiveEngineering:storage:5>,
	<ImmersiveEngineering:storage:6>,
	<ImmersiveEngineering:storageSlab>,
	<ImmersiveEngineering:storageSlab:1>,
	<ImmersiveEngineering:storageSlab:2>,
	<ImmersiveEngineering:storageSlab:3>,
	<ImmersiveEngineering:storageSlab:4>,
	<ImmersiveEngineering:storageSlab:5>,
	<ImmersiveEngineering:storageSlab:6>,
	<ImmersiveEngineering:metal>,
	<ImmersiveEngineering:metal:1>,
	<ImmersiveEngineering:metal:2>,
	<ImmersiveEngineering:metal:3>,
	<ImmersiveEngineering:metal:4>,
	<ImmersiveEngineering:metal:5>,
	<ImmersiveEngineering:metal:6>,
	<ImmersiveEngineering:metal:7>,
	<ImmersiveEngineering:metal:8>,
	<ImmersiveEngineering:metal:9>,
	<ImmersiveEngineering:metal:10>,
	<ImmersiveEngineering:metal:11>,
	<ImmersiveEngineering:metal:12>,
	<ImmersiveEngineering:metal:13>,
	<ImmersiveEngineering:metal:14>,
	<ImmersiveEngineering:metal:15>,
	<ImmersiveEngineering:metal:16>,
	<ImmersiveEngineering:metal:21>,
	<ImmersiveEngineering:metal:22>,
	<ImmersiveEngineering:metal:23>,
	<ImmersiveEngineering:metal:24>,
	<ImmersiveEngineering:metal:25>,
	<ImmersiveEngineering:metal:26>,
	<ImmersiveEngineering:metal:27>,
	<ImmersiveEngineering:metal:28>,
	<ImmersiveEngineering:metal:29>,
	<ImmersiveEngineering:metal:30>,
	<ImmersiveEngineering:metal:31>,
	<ImmersiveEngineering:metal:32>,
	<ImmersiveEngineering:metal:33>,
	<ImmersiveEngineering:metal:34>,
	<ImmersiveEngineering:metal:35>,
	<ImmersiveEngineering:metal:36>,
	<ImmersiveEngineering:metal:37>,
	<ImmersiveEngineering:metal:38>,
] as IItemStack[];

var removeFromOredicts = [
	<ore:stoneAndesite>,
	<ore:stoneDiorite>,
	<ore:stoneGranite>,
	<ore:stoneAndesitePolished>,
	<ore:stoneDioritePolished>,
	<ore:stoneGranitePolished>,
	<ore:nuggetIron>,
	<ore:paxelSteel>,
	<ore:blockAmber>,
	<ore:oreCopper>,
	<ore:oreDeepslateCopper>,
	<ore:oreTin>,
	<ore:oreDeepslateTin>,
	<ore:oreLead>,
	<ore:oreSilver>,
	<ore:oreAluminum>,
	<ore:oreNickel>,
	<ore:blockCopper>,
	<ore:blockLead>,
	<ore:blockTin>,
	<ore:blockBronze>,
	<ore:blockSilver>,
	<ore:blockNickel>,
	<ore:blockElectrum>,
	<ore:blockConstantan>,
	<ore:blockCupronickel>,
	<ore:blockCobalt>,
	<ore:blockArdite>,
	<ore:blockManyullyn>,
	<ore:blockAluminum>,
	<ore:blockAluminium>,
	<ore:blockAluminumBrass>,
	<ore:blockAluminiumBrass>,
	<ore:blockAlumite>,
	<ore:blockSteel>,
	<ore:blockEnder>,
	<ore:ingotCopper>,
	<ore:ingotLead>,
	<ore:ingotSilver>,
	<ore:ingotNickel>,
	<ore:ingotRefinedLapis>,
	<ore:ingotElectrum>,
	<ore:ingotConstantan>,
	<ore:ingotCupronickel>,
	<ore:ingotSteel>,
	<ore:ingotTin>,
	<ore:ingotBronze>,
	<ore:ingotAluminum>,
	<ore:ingotRefinedObsidian>,
	<ore:ingotRefinedGlowstone>,
	<ore:nuggetGold>,
	<ore:nuggetCopper>,
	<ore:nuggetLead>,
	<ore:nuggetAluminum>,
	<ore:nuggetTin>,
	<ore:nuggetSilver>,
	<ore:nuggetNickel>,
	<ore:nuggetElectrum>,
	<ore:nuggetConstantan>,
	<ore:nuggetCupronickel>,
	<ore:nuggetManasteel>,
	<ore:nuggetAluminum>,
	<ore:nuggetAluminium>,
	<ore:plateIron>,
	<ore:plateAluminum>,
	<ore:plateLead>,
	<ore:plateCopper>,
	<ore:plateElectrum>,
	<ore:plateConstantan>,
	<ore:plateNickel>,
	<ore:plateSilver>,
	<ore:plateSteel>,
	<ore:dustIron>,
	<ore:dustGold>,
	<ore:dustCopper>,
	<ore:dustAluminum>,
	<ore:dustTin>,
	<ore:dustLead>,
	<ore:dustSilver>,
	<ore:dustOsmium>,
	<ore:dustNickel>,
	<ore:dustConstantan>,
	<ore:dustCupronickel>,
	<ore:dye>,
	<ore:dyeBlack>,	
	<ore:dyeBlue>,
	<ore:dyeBrown>,
	<ore:dyeWhite>,
	<ore:dyeGreen>,
	<ore:blockPrismarine>,
	<ore:blockPrismarineBrick>,
	<ore:blockPrismarineDark>,
	<ore:shardPrismarine>,
	<ore:gemPrismarine>,
	<ore:crystalPrismarine>,
	<ore:dustPrismarine>
] as IOreDictEntry[];

var groupsToRemoveFromChisel = [
	"netherlicious_Blackstone",
	"netherlicious_Basalt",
	"netherlicious_SoulSandStone",
	"quartz",
	"cobblestone",
	"stonebrick",
	"aluminum_stairs",
	"limestone_slab",
	"limestone_stairs",
	"marble_pillar_slab",
	"marble_slab",
	"marble_stairs",
	"ice_stairs",
	"packedice_stairs",
	"hempcrete",
	"hempcretesand",
	"woolen_clay",
	"voidstonePillar",
	"voidstonePillar2"
] as IData[];

var axesToTag = [
	<materialis:flint_axe:*>,
	<materialis:bronze_axe:*>,
	<materialis:steel_axe:*>,
	<minecraft:iron_axe:*>,
	<minecraft:diamond_axe:*>,
	<minecraft:golden_axe:*>,
	<AWWayofTime:boundAxe:*>,
	<Botania:manasteelAxe:*>,
	<Botania:elementiumAxe:*>,
	<Botania:terraAxe:*>,
	<ForbiddenMagic:MorphAxe:*>,
	<TaintedMagic:ItemShadowmetalAxe:*>,
	<Thaumcraft:ItemAxeThaumium:*>,
	<Thaumcraft:ItemAxeElemental:*>,
	<Thaumcraft:ItemAxeVoid:*>,
	<aether_legacy:zanite_axe:*>,
	<aether_legacy:gravitite_axe:*>,
	<aether_legacy:valkyrie_axe:*>,
	<etfuturum:netherite_axe:*>,
	<netherlicious:EfrineAxe:*>,
	<thebetweenlands:betweenstoneAxe:*>,
	<thebetweenlands:octineAxe:*>,
	<thebetweenlands:valoniteAxe:*>,
] as IItemStack[];

var sawsToTag = [
	<ForgeMicroblock:sawFlint:*>,
	<ForgeMicroblock:sawBronze:*>,
	<ForgeMicroblock:sawIron:*>,
	<ForgeMicroblock:sawThaumium:*>,
	<ForgeMicroblock:sawManasteel:*>,
	<ForgeMicroblock:sawGold:*>,
	<ForgeMicroblock:sawDiamond:*>,
	<ForgeMicroblock:sawSteel:*>,
] as IItemStack[];

for i, items in itemsToRemove {
	recipes.remove(items);

	for j, oredicts in removeFromOredicts {
		if(oredicts in items) {
			oredicts.remove(items);
		}
	}
}

for i, items in oresToRemove {
	recipes.remove(items);
	furnace.remove(items);
	mods.immersiveengineering.Crusher.removeRecipe(items);
	mods.immersiveengineering.MetalPress.removeRecipe(items);
	mods.immersiveengineering.ArcFurnace.removeRecipe(items);

	for j, oredicts in removeFromOredicts {
		if(oredicts in items) {
			oredicts.remove(items);
		}
	}
}

for i, items in axesToTag {
	<ore:toolAxe>.add(items);
}

for i, items in sawsToTag {
	<ore:toolSaw>.add(items);
}

for g, groups in groupsToRemoveFromChisel {
	mods.chisel.Groups.removeGroup(groups);
}

recipes.remove(<minecraft:sandstone:1>);
recipes.remove(<minecraft:sandstone:2>);
recipes.remove(<minecraft:stonebrick:1>);
recipes.remove(<minecraft:mossy_cobblestone>);
recipes.remove(<minecraft:quartz_block:1>);
recipes.remove(<etfuturum:red_sandstone:2>);

furnace.remove(<etfuturum:copper_ingot>);
furnace.remove(<ImmersiveEngineering:metal:*>);

recipes.removeShapeless(<WitchingGadgets:WG_MetalDevice>);

mods.thaumcraft.Arcane.removeRecipe(<WitchingGadgets:item.WG_Kama:*>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicHorizons:focusLiquefaction>);

recipes.removeShapeless(<Botania:customBrick:4>, [<Botania:customBrick:15>]);
mods.chisel.Groups.removeVariation(<Botania:endStoneBrick>);

recipes.remove(<chisel:purpur>);
recipes.addShaped(<chisel:purpur> * 4, [
	[<etfuturum:chorus_fruit_popped>, <etfuturum:chorus_fruit_popped>],
	[<etfuturum:chorus_fruit_popped>, <etfuturum:chorus_fruit_popped>]
]);

<ore:gemQuartz>.remove(<netherlicious:VoidQuartzItem>);
<ore:stickWood>.remove(<BiomesOPlenty:bamboo>);
<ore:stickWood>.remove(<BiomesOPlenty:plants:8>);
<ore:stickWood>.remove(<aether_legacy:skyroot_stick>);

<ore:stickWoodHalf>.add(<BiomesOPlenty:bamboo>);
<ore:stickWoodHalf>.add(<BiomesOPlenty:plants:8>);
recipes.addShaped(<minecraft:stick> * 2, [
	[<ore:stickWoodHalf>],
	[<ore:stickWoodHalf>]
]);